import os
from pathlib import Path

DATA_DIR = Path(os.environ.get("MARKET_DATA_DIR", str(Path.home() / ".market_data" / "parquet")))
LOG_DIR = Path(os.environ.get("MARKET_DATA_LOG_DIR", str(Path.home() / ".market_data" / "logs")))

DEFAULT_TICKERS: list[str] = [
    # --- S&P 500 components (as of 2026-04) ---
    "A",
    "AAPL",
    "ABBV",
    "ABNB",
    "ABT",
    "ACGL",
    "ACN",
    "ADBE",
    "ADI",
    "ADM",
    "ADP",
    "ADSK",
    "AEE",
    "AEP",
    "AES",
    "AFL",
    "AIG",
    "AIZ",
    "AJG",
    "AKAM",
    "ALB",
    "ALGN",
    "ALL",
    "ALLE",
    "AMAT",
    "AMCR",
    "AMD",
    "AME",
    "AMGN",
    "AMP",
    "AMT",
    "AMZN",
    "ANET",
    "AON",
    "AOS",
    "APA",
    "APD",
    "APH",
    "APO",
    "APP",
    "APTV",
    "ARE",
    "ARES",
    "ATO",
    "AVB",
    "AVGO",
    "AVY",
    "AWK",
    "AXON",
    "AXP",
    "AZO",
    "BA",
    "BAC",
    "BALL",
    "BAX",
    "BBY",
    "BDX",
    "BEN",
    "BF-B",
    "BG",
    "BIIB",
    "BK",
    "BKNG",
    "BKR",
    "BLDR",
    "BLK",
    "BMY",
    "BR",
    "BRK-B",
    "BRO",
    "BSX",
    "BX",
    "BXP",
    "C",
    "CAG",
    "CAH",
    "CARR",
    "CAT",
    "CB",
    "CBOE",
    "CBRE",
    "CCI",
    "CCL",
    "CDNS",
    "CDW",
    "CEG",
    "CF",
    "CFG",
    "CHD",
    "CHRW",
    "CHTR",
    "CI",
    "CIEN",
    "CINF",
    "CL",
    "CLX",
    "CMCSA",
    "CME",
    "CMG",
    "CMI",
    "CMS",
    "CNC",
    "CNP",
    "COF",
    "COHR",
    "COIN",
    "COO",
    "COP",
    "COR",
    "COST",
    "CPAY",
    "CPB",
    "CPRT",
    "CPT",
    "CRH",
    "CRL",
    "CRM",
    "CRWD",
    "CSCO",
    "CSGP",
    "CSX",
    "CTAS",
    "CTRA",
    "CTSH",
    "CTVA",
    "CVNA",
    "CVS",
    "CVX",
    "D",
    "DAL",
    "DASH",
    "DD",
    "DDOG",
    "DE",
    "DECK",
    "DELL",
    "DG",
    "DGX",
    "DHI",
    "DHR",
    "DIS",
    "DLR",
    "DLTR",
    "DOC",
    "DOV",
    "DOW",
    "DPZ",
    "DRI",
    "DTE",
    "DUK",
    "DVA",
    "DVN",
    "DXCM",
    "EA",
    "EBAY",
    "ECL",
    "ED",
    "EFX",
    "EG",
    "EIX",
    "EL",
    "ELV",
    "EME",
    "EMR",
    "EOG",
    "EPAM",
    "EQIX",
    "EQR",
    "EQT",
    "ERIE",
    "ES",
    "ESS",
    "ETN",
    "ETR",
    "EVRG",
    "EW",
    "EXC",
    "EXE",
    "EXPD",
    "EXPE",
    "EXR",
    "F",
    "FANG",
    "FAST",
    "FCX",
    "FDS",
    "FDX",
    "FE",
    "FFIV",
    "FICO",
    "FIS",
    "FISV",
    "FITB",
    "FIX",
    "FOX",
    "FOXA",
    "FRT",
    "FSLR",
    "FTNT",
    "FTV",
    "GD",
    "GDDY",
    "GE",
    "GEHC",
    "GEN",
    "GEV",
    "GILD",
    "GIS",
    "GL",
    "GLW",
    "GM",
    "GNRC",
    "GOOG",
    "GOOGL",
    "GPC",
    "GPN",
    "GRMN",
    "GS",
    "GWW",
    "HAL",
    "HAS",
    "HBAN",
    "HCA",
    "HD",
    "HIG",
    "HII",
    "HLT",
    "HOLX",
    "HON",
    "HOOD",
    "HPE",
    "HPQ",
    "HRL",
    "HSIC",
    "HST",
    "HSY",
    "HUBB",
    "HUM",
    "HWM",
    "IBKR",
    "IBM",
    "ICE",
    "IDXX",
    "IEX",
    "IFF",
    "INCY",
    "INTC",
    "INTU",
    "INVH",
    "IP",
    "IQV",
    "IR",
    "IRM",
    "ISRG",
    "IT",
    "ITW",
    "IVZ",
    "J",
    "JBHT",
    "JBL",
    "JCI",
    "JKHY",
    "JNJ",
    "JPM",
    "KDP",
    "KEY",
    "KEYS",
    "KHC",
    "KIM",
    "KKR",
    "KLAC",
    "KMB",
    "KMI",
    "KO",
    "KR",
    "KVUE",
    "L",
    "LDOS",
    "LEN",
    "LH",
    "LHX",
    "LII",
    "LIN",
    "LITE",
    "LLY",
    "LMT",
    "LNT",
    "LOW",
    "LRCX",
    "LULU",
    "LUV",
    "LVS",
    "LYB",
    "LYV",
    "MA",
    "MAA",
    "MAR",
    "MAS",
    "MCD",
    "MCHP",
    "MCK",
    "MCO",
    "MDLZ",
    "MDT",
    "MET",
    "META",
    "MGM",
    "MKC",
    "MLM",
    "MMM",
    "MNST",
    "MO",
    "MOS",
    "MPC",
    "MPWR",
    "MRK",
    "MRNA",
    "MRSH",
    "MS",
    "MSCI",
    "MSFT",
    "MSI",
    "MTB",
    "MTD",
    "MU",
    "NCLH",
    "NDAQ",
    "NDSN",
    "NEE",
    "NEM",
    "NFLX",
    "NI",
    "NKE",
    "NOC",
    "NOW",
    "NRG",
    "NSC",
    "NTAP",
    "NTRS",
    "NUE",
    "NVDA",
    "NVR",
    "NWS",
    "NWSA",
    "NXPI",
    "O",
    "ODFL",
    "OKE",
    "OMC",
    "ON",
    "ORCL",
    "ORLY",
    "OTIS",
    "OXY",
    "PANW",
    "PAYX",
    "PCAR",
    "PCG",
    "PEG",
    "PEP",
    "PFE",
    "PFG",
    "PG",
    "PGR",
    "PH",
    "PHM",
    "PKG",
    "PLD",
    "PLTR",
    "PM",
    "PNC",
    "PNR",
    "PNW",
    "PODD",
    "POOL",
    "PPG",
    "PPL",
    "PRU",
    "PSA",
    "PSKY",
    "PSX",
    "PTC",
    "PWR",
    "PYPL",
    "Q",
    "QCOM",
    "RCL",
    "REG",
    "REGN",
    "RF",
    "RJF",
    "RL",
    "RMD",
    "ROK",
    "ROL",
    "ROP",
    "ROST",
    "RSG",
    "RTX",
    "RVTY",
    "SATS",
    "SBAC",
    "SBUX",
    "SCHW",
    "SHW",
    "SJM",
    "SLB",
    "SMCI",
    "SNA",
    "SNDK",
    "SNPS",
    "SO",
    "SOLV",
    "SPG",
    "SPGI",
    "SRE",
    "STE",
    "STLD",
    "STT",
    "STX",
    "STZ",
    "SW",
    "SWK",
    "SWKS",
    "SYF",
    "SYK",
    "SYY",
    "T",
    "TAP",
    "TDG",
    "TDY",
    "TECH",
    "TEL",
    "TER",
    "TFC",
    "TGT",
    "TJX",
    "TKO",
    "TMO",
    "TMUS",
    "TPL",
    "TPR",
    "TRGP",
    "TRMB",
    "TROW",
    "TRV",
    "TSCO",
    "TSLA",
    "TSN",
    "TT",
    "TTD",
    "TTWO",
    "TXN",
    "TXT",
    "TYL",
    "UAL",
    "UBER",
    "UDR",
    "UHS",
    "ULTA",
    "UNH",
    "UNP",
    "UPS",
    "URI",
    "USB",
    "V",
    "VICI",
    "VLO",
    "VLTO",
    "VMC",
    "VRSK",
    "VRSN",
    "VRT",
    "VRTX",
    "VST",
    "VTR",
    "VTRS",
    "VZ",
    "WAB",
    "WAT",
    "WBD",
    "WDAY",
    "WDC",
    "WEC",
    "WELL",
    "WFC",
    "WM",
    "WMB",
    "WMT",
    "WRB",
    "WSM",
    "WST",
    "WTW",
    "WY",
    "WYNN",
    "XEL",
    "XOM",
    "XYL",
    "XYZ",
    "YUM",
    "ZBH",
    "ZBRA",
    "ZTS",
    # --- ETFs ---
    "QQQ",
    "SPY",
    "IWM",
    "MTUM",
    "XLK",
    "XLF",
    "XLV",
    "XLI",
    "XLY",
    "XLE",
    "TLT",
    "IEF",
    "GLD",
    "USO",
    # --- Indices ---
    "^VIX",
    # --- Crypto ---
    "BTC-USD",
    "ETH-USD",
    # --- Forex ---
    "EURUSD=X",
    "GBPUSD=X",
]

TICKER_LIST_FILE: str = os.environ.get("MARKET_DATA_TICKER_LIST_FILE", "")
BATCH_SIZE: int = int(os.environ.get("MARKET_DATA_BATCH_SIZE", "50"))

LOOKBACK_DAYS = int(os.environ.get("MARKET_DATA_LOOKBACK_DAYS", "365"))
MIN_ROLLING_DAYS = 30
FETCH_INTERVAL = "1d"

VALID_INTERVALS: list[str] = ["1d", "1h", "15m", "5m"]
DEFAULT_INTERVAL = "1d"
MAX_RETRIES = int(os.environ.get("MARKET_DATA_MAX_RETRIES", "3"))
RETRY_DELAY_RANGE = (1.0, 3.0)
FETCH_CONCURRENCY = int(os.environ.get("MARKET_DATA_FETCH_CONCURRENCY", "4"))

_default_cors = "http://localhost:3000,http://127.0.0.1:3000"
CORS_ORIGINS: list[str] = [
    o.strip() for o in os.environ.get("MARKET_DATA_CORS_ORIGINS", _default_cors).split(",") if o.strip()
]

WS_POLL_INTERVAL = int(os.environ.get("MARKET_DATA_WS_POLL_INTERVAL", "5"))
WS_HEARTBEAT_INTERVAL = int(os.environ.get("MARKET_DATA_WS_HEARTBEAT_INTERVAL", "15"))

CACHE_TTL_SECONDS = int(os.environ.get("MARKET_DATA_CACHE_TTL", "120"))
CACHE_MAX_ENTRIES = int(os.environ.get("MARKET_DATA_CACHE_MAX_ENTRIES", "4096"))

API_KEY: str | None = os.environ.get("MARKET_DATA_API_KEY")

# --- Notification channels ---
TELEGRAM_BOT_TOKEN: str | None = os.environ.get("TELEGRAM_BOT_TOKEN")
TELEGRAM_DEFAULT_CHAT_ID: str | None = os.environ.get("TELEGRAM_DEFAULT_CHAT_ID")

SMTP_HOST: str = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT: int = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USERNAME: str | None = os.environ.get("SMTP_USERNAME")
SMTP_PASSWORD: str | None = os.environ.get("SMTP_PASSWORD")
SMTP_FROM: str | None = os.environ.get("SMTP_FROM")

# --- AI / Ollama ---
TWELVEDATA_API_KEY: str | None = os.environ.get("TWELVEDATA_API_KEY")

OLLAMA_HOST: str = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
OLLAMA_MODEL: str = os.environ.get("OLLAMA_MODEL", "qwen3:32b")
OLLAMA_TIMEOUT: int = int(os.environ.get("OLLAMA_TIMEOUT", "180"))


def get_tickers() -> list[str]:
    """Load tickers from TICKER_LIST_FILE if set, otherwise use DEFAULT_TICKERS."""
    if TICKER_LIST_FILE and Path(TICKER_LIST_FILE).expanduser().exists():
        tickers = [
            line.strip().upper()
            for line in Path(TICKER_LIST_FILE).expanduser().read_text().splitlines()
            if line.strip() and not line.strip().startswith("#")
        ]
        if tickers:
            return list(dict.fromkeys(tickers))  # dedupe, preserve order
    return DEFAULT_TICKERS
